
export const AGREGAREVENTO = 'AGREGAREVENTO';
export const BORRAREVENTO = 'BORRAREVENTO';
export const AGREGARPERSONA= 'AGREGARPERSONA';
export const BORRARPERSONA='BORRARPERSONA';
export const CAMBIARASISTENCIA= 'CAMBIARASISTENCIA';
